name: kaong_fermentation_app
description: "An application for the Automated Kaong Wine Fermentation System Design Project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Default Icons ---
  cupertino_icons: ^1.0.8

  # --- Firebase Services (For Realtime Database) ---
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0

  # --- Modern UI Components ---
  percent_indicator: ^4.2.3  
  glassmorphism: ^3.0.0      
  intl: ^0.19.0              

  # --- Auto-Update & Network ---
  http: ^1.2.0               
  package_info_plus: ^5.0.1  
  r_upgrade: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true